// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum BallMaxSpeedOption : sbyte
{
 Default = 0,
 Slow = 1,
 Fast = 2,
 Super_Fast = 3,
};


}
