// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum BallWeightOption : sbyte
{
 Default = 0,
 Light = 1,
 Heavy = 2,
 Super_Light = 3,
};


}
