// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum BallBouncinessOption : sbyte
{
 Default = 0,
 Low = 1,
 High = 2,
 Super_High = 3,
};


}
