// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum BallTypeOption : sbyte
{
 Default = 0,
 Cube = 1,
 Puck = 2,
 Basketball = 3,
};


}
