// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum BallSizeOption : sbyte
{
 Default = 0,
 Small = 1,
 Large = 2,
 Gigantic = 3,
};


}
