// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum BoostStrengthOption : sbyte
{
 One = 0,
 OneAndAHalf = 1,
 Two = 2,
 Ten = 3,
};


}
