// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum CollisionShape : byte
{
 NONE = 0,
 BoxShape = 1,
 SphereShape = 2,
 CylinderShape = 3,
};


}
