// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct CylinderShape : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CylinderShape GetRootAsCylinderShape(ByteBuffer _bb) { return GetRootAsCylinderShape(_bb, new CylinderShape()); }
  public static CylinderShape GetRootAsCylinderShape(ByteBuffer _bb, CylinderShape obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CylinderShape __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Diameter { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Height { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<CylinderShape> CreateCylinderShape(FlatBufferBuilder builder,
      float diameter = 0.0f,
      float height = 0.0f) {
    builder.StartObject(2);
    CylinderShape.AddHeight(builder, height);
    CylinderShape.AddDiameter(builder, diameter);
    return CylinderShape.EndCylinderShape(builder);
  }

  public static void StartCylinderShape(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddDiameter(FlatBufferBuilder builder, float diameter) { builder.AddFloat(0, diameter, 0.0f); }
  public static void AddHeight(FlatBufferBuilder builder, float height) { builder.AddFloat(1, height, 0.0f); }
  public static Offset<CylinderShape> EndCylinderShape(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CylinderShape>(o);
  }
};


}
