// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum DemolishOption : sbyte
{
 Default = 0,
 Disabled = 1,
 Friendly_Fire = 2,
 On_Contact = 3,
 On_Contact_FF = 4,
};


}
