// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct DesiredBoostState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DesiredBoostState GetRootAsDesiredBoostState(ByteBuffer _bb) { return GetRootAsDesiredBoostState(_bb, new DesiredBoostState()); }
  public static DesiredBoostState GetRootAsDesiredBoostState(ByteBuffer _bb, DesiredBoostState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DesiredBoostState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Float? RespawnTime { get { int o = __p.__offset(4); return o != 0 ? (Float?)(new Float()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartDesiredBoostState(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRespawnTime(FlatBufferBuilder builder, Offset<Float> respawnTimeOffset) { builder.AddStruct(0, respawnTimeOffset.Value, 0); }
  public static Offset<DesiredBoostState> EndDesiredBoostState(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DesiredBoostState>(o);
  }
};


}
