// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct DropShotBallInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DropShotBallInfo GetRootAsDropShotBallInfo(ByteBuffer _bb) { return GetRootAsDropShotBallInfo(_bb, new DropShotBallInfo()); }
  public static DropShotBallInfo GetRootAsDropShotBallInfo(ByteBuffer _bb, DropShotBallInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DropShotBallInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float AbsorbedForce { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int DamageIndex { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float ForceAccumRecent { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<DropShotBallInfo> CreateDropShotBallInfo(FlatBufferBuilder builder,
      float absorbedForce = 0.0f,
      int damageIndex = 0,
      float forceAccumRecent = 0.0f) {
    builder.StartObject(3);
    DropShotBallInfo.AddForceAccumRecent(builder, forceAccumRecent);
    DropShotBallInfo.AddDamageIndex(builder, damageIndex);
    DropShotBallInfo.AddAbsorbedForce(builder, absorbedForce);
    return DropShotBallInfo.EndDropShotBallInfo(builder);
  }

  public static void StartDropShotBallInfo(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddAbsorbedForce(FlatBufferBuilder builder, float absorbedForce) { builder.AddFloat(0, absorbedForce, 0.0f); }
  public static void AddDamageIndex(FlatBufferBuilder builder, int damageIndex) { builder.AddInt(1, damageIndex, 0); }
  public static void AddForceAccumRecent(FlatBufferBuilder builder, float forceAccumRecent) { builder.AddFloat(2, forceAccumRecent, 0.0f); }
  public static Offset<DropShotBallInfo> EndDropShotBallInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DropShotBallInfo>(o);
  }
};


}
