// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum GameMode : sbyte
{
 Soccer = 0,
 Hoops = 1,
 Dropshot = 2,
 Hockey = 3,
 Rumble = 4,
};


}
