// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum GameSpeedOption : sbyte
{
 Default = 0,
 Slo_Mo = 1,
 Time_Warp = 2,
};


}
