// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

/// A normal human player
public struct HumanPlayer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static HumanPlayer GetRootAsHumanPlayer(ByteBuffer _bb) { return GetRootAsHumanPlayer(_bb, new HumanPlayer()); }
  public static HumanPlayer GetRootAsHumanPlayer(ByteBuffer _bb, HumanPlayer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public HumanPlayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartHumanPlayer(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<HumanPlayer> EndHumanPlayer(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HumanPlayer>(o);
  }
};


}
