// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum MatchLength : sbyte
{
 Five_Minutes = 0,
 Ten_Minutes = 1,
 Twenty_Minutes = 2,
 Unlimited = 3,
};


}
