// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum MaxScore : sbyte
{
 Unlimited = 0,
 One_Goal = 1,
 Three_Goals = 2,
 Five_Goals = 3,
};


}
