// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum OvertimeOption : sbyte
{
 Unlimited = 0,
 Five_Max_First_Score = 1,
 Five_Max_Random_Team = 2,
};


}
