// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum PlayerClass : byte
{
 NONE = 0,
 RLBotPlayer = 1,
 HumanPlayer = 2,
 PsyonixBotPlayer = 3,
 PartyMemberBotPlayer = 4,
};


}
