// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

/// A psyonix bot, e.g. All Star bot
public struct PsyonixBotPlayer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PsyonixBotPlayer GetRootAsPsyonixBotPlayer(ByteBuffer _bb) { return GetRootAsPsyonixBotPlayer(_bb, new PsyonixBotPlayer()); }
  public static PsyonixBotPlayer GetRootAsPsyonixBotPlayer(ByteBuffer _bb, PsyonixBotPlayer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PsyonixBotPlayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float BotSkill { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<PsyonixBotPlayer> CreatePsyonixBotPlayer(FlatBufferBuilder builder,
      float botSkill = 0.0f) {
    builder.StartObject(1);
    PsyonixBotPlayer.AddBotSkill(builder, botSkill);
    return PsyonixBotPlayer.EndPsyonixBotPlayer(builder);
  }

  public static void StartPsyonixBotPlayer(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddBotSkill(FlatBufferBuilder builder, float botSkill) { builder.AddFloat(0, botSkill, 0.0f); }
  public static Offset<PsyonixBotPlayer> EndPsyonixBotPlayer(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PsyonixBotPlayer>(o);
  }
};


}
