// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct QuickChatMessages : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static QuickChatMessages GetRootAsQuickChatMessages(ByteBuffer _bb) { return GetRootAsQuickChatMessages(_bb, new QuickChatMessages()); }
  public static QuickChatMessages GetRootAsQuickChatMessages(ByteBuffer _bb, QuickChatMessages obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public QuickChatMessages __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public QuickChat? Messages(int j) { int o = __p.__offset(4); return o != 0 ? (QuickChat?)(new QuickChat()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MessagesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<QuickChatMessages> CreateQuickChatMessages(FlatBufferBuilder builder,
      VectorOffset messagesOffset = default(VectorOffset)) {
    builder.StartObject(1);
    QuickChatMessages.AddMessages(builder, messagesOffset);
    return QuickChatMessages.EndQuickChatMessages(builder);
  }

  public static void StartQuickChatMessages(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddMessages(FlatBufferBuilder builder, VectorOffset messagesOffset) { builder.AddOffset(0, messagesOffset.Value, 0); }
  public static VectorOffset CreateMessagesVector(FlatBufferBuilder builder, Offset<QuickChat>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartMessagesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<QuickChatMessages> EndQuickChatMessages(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<QuickChatMessages>(o);
  }
};


}
