// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum RespawnTimeOption : sbyte
{
 Three_Seconds = 0,
 Two_Seconds = 1,
 One_Seconds = 2,
 Disable_Goal_Reset = 3,
};


}
