// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

/// A bot controlled by the RLBot framework
public struct RLBotPlayer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RLBotPlayer GetRootAsRLBotPlayer(ByteBuffer _bb) { return GetRootAsRLBotPlayer(_bb, new RLBotPlayer()); }
  public static RLBotPlayer GetRootAsRLBotPlayer(ByteBuffer _bb, RLBotPlayer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RLBotPlayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRLBotPlayer(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<RLBotPlayer> EndRLBotPlayer(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RLBotPlayer>(o);
  }
};


}
