// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

public enum SeriesLengthOption : sbyte
{
 Unlimited = 0,
 Three_Games = 1,
 Five_Games = 2,
 Seven_Games = 3,
};


}
