// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

/// A minimal version of the game tick packet, useful when bandwidth needs to be conserved.
public struct TinyPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static TinyPacket GetRootAsTinyPacket(ByteBuffer _bb) { return GetRootAsTinyPacket(_bb, new TinyPacket()); }
  public static TinyPacket GetRootAsTinyPacket(ByteBuffer _bb, TinyPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public TinyPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public TinyPlayer? Players(int j) { int o = __p.__offset(4); return o != 0 ? (TinyPlayer?)(new TinyPlayer()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PlayersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public TinyBall? Ball { get { int o = __p.__offset(6); return o != 0 ? (TinyBall?)(new TinyBall()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<TinyPacket> CreateTinyPacket(FlatBufferBuilder builder,
      VectorOffset playersOffset = default(VectorOffset),
      Offset<TinyBall> ballOffset = default(Offset<TinyBall>)) {
    builder.StartObject(2);
    TinyPacket.AddBall(builder, ballOffset);
    TinyPacket.AddPlayers(builder, playersOffset);
    return TinyPacket.EndTinyPacket(builder);
  }

  public static void StartTinyPacket(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPlayers(FlatBufferBuilder builder, VectorOffset playersOffset) { builder.AddOffset(0, playersOffset.Value, 0); }
  public static VectorOffset CreatePlayersVector(FlatBufferBuilder builder, Offset<TinyPlayer>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartPlayersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBall(FlatBufferBuilder builder, Offset<TinyBall> ballOffset) { builder.AddOffset(1, ballOffset.Value, 0); }
  public static Offset<TinyPacket> EndTinyPacket(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<TinyPacket>(o);
  }
};


}
